stages:
  - build
  - test

##################
# Build
##################

build_debian10_gcc:
  stage: build
  tags:
    - docker
  image: registry.git.vikingsoftware.com/esa/taste3-ci-image:latest
  script:
    - mkdir -p build; cd build
    - cmake -GNinja ..
    - ninja
  artifacts:
    paths:
      - build
    expire_in: 1 day

build_windows:
  stage: build
  tags:
    - win10
    - vs2019
    - x64
    - grantlee
  script:
    - ./scripts/build_windows.ps1

##################
# TEST
##################

test_docker:
  stage: test
  tags:
    - docker
  image: registry.git.vikingsoftware.com/esa/taste3-ci-image:latest
  script:
    - ./scripts/run_tests.sh build
  dependencies:
    - build_debian10_gcc
  artifacts:
    reports:
      junit: build/tst_*-result.xml
