stages:
  - build
  - test
  - deploy

##################
# Build
##################
build_debian10_gcc:
  stage: build
  tags:
    - docker
  image: registry.git.vikingsoftware.com/esa/taste3-ci-image:latest
  script:
    - mkdir -p build; cd build
    - cmake -GNinja ..
    - ninja
  cache:
    key: asn1scc
    paths:
      - build/asn1scc_bin
  artifacts:
    paths:
      - build
    expire_in: 1 day

build_windows:
  stage: build
  tags:
    - docker-windows
  image: registry.git.vikingsoftware.com/esa/esa-ci-image-windows:latest
  script:
    - mkdir build; cd build
    - cmake -GNinja -DCMAKE_PREFIX_PATH="$Env:QTDIR" -DQT_QMAKE_EXECUTABLE="$Env:QTDIR/bin/qmake.exe" ..
    - ninja

##################
# TEST
##################
test_docker:
  stage: test
  tags:
    - docker
  image: registry.git.vikingsoftware.com/esa/taste3-ci-image:latest
  script:
    - ./scripts/run_tests.sh build
  dependencies:
    - build_debian10_gcc
  cache:
    key: asn1scc
    paths:
      - build/asn1scc_bin
  artifacts:
    reports:
      junit: build/tst_*-result.xml

##################
# Deployment
##################
documentation:
  stage: deploy
  tags:
    - docker
  image: registry.git.vikingsoftware.com/esa/taste3-ci-image:latest
  script:
    - ./scripts/generate_documentation.sh
  cache:
    key: asn1scc
    paths:
      - build/asn1scc_bin
  artifacts:
    paths:
      - doc/doxygen/html
    expire_in: 4 weeks
  only:
    - master

debian_package:
  stage: deploy
  tags:
    - docker
  image: registry.git.vikingsoftware.com/esa/taste3-ci-image:latest
  script:
  - mkdir -p build; cd build
  - cmake -GNinja .. -DBUILD_PATCH_NUMBER=$CI_BUILD_ID -DENABLE_TESTS=OFF
  - cmake --build . --target all
  - cpack
  - cd ..; mkdir -p package; cp build/*.deb package
  cache:
    key: asn1scc
    paths:
      - build/asn1scc_bin
  artifacts:
    paths:
      - package
    expire_in: 4 weeks
  only:
    - master
