stages:
  - build

build_debian10_gcc:
  stage: build
  tags:
    - docker
  image: registry.git.vikingsoftware.com/vs/ci-images/debian_10_cpp:latest
  script:
    - mkdir -p build; cd build
    - qmake -recursive ..
    - make -j 8
