stages:
  - build
  - test

##################
# Build
##################

# Docker based Linux build (because of tag docker - see CI runners tags)
build_linux_gcc:
  stage: build
  tags:
    - docker
  image: registry.git.vikingsoftware.com/vs/ci-images/ubuntu_bionic_qt5.11.1_cpp:latest
  script:
    - apt-get update -yq
    - apt-get install -y uuid-dev default-jre
    - mkdir -p build; cd build
    - qmake -recursive ..
    - make -j 8
  artifacts:
    paths:
      - build
      - libs/msclibrary/parser
    expire_in: 1 day

build_linux_clang:
  stage: build
  tags:
    - docker
  image: registry.git.vikingsoftware.com/vs/ci-images/ubuntu_bionic_qt5.11.1_cpp:latest
  script: 
    - apt-get update -yq
    - apt-get install -y uuid-dev default-jre
    - mkdir -p build_clang
    - cd build_clang
    - qmake QMAKE_CC=clang QMAKE_CXX=clang++ -recursive ..
    - make -j 8

# MacOS Shell (because of tag macOS - see CI runners tags)
build_MacOS:
  stage: build
  tags:
    - macOS
  script:
    - mkdir build_macos
    - cd build_macos
    - qmake ..
    - make -j 8

build_Windows:
  stage: build
  tags:
    - win10
    - vs2017
    - x64
  script:
    - scripts\build_windows.bat

##################
# TEST
##################

test_docker:
  stage: test
  tags:
    - docker
  image: registry.git.vikingsoftware.com/vs/ci-images/ubuntu_bionic_qt5.11.1_cpp:latest
  script:
    - find build | xargs touch # Avoid rebuilding
    - cd build
    - export QT_QPA_PLATFORM=offscreen
    - make check
  dependencies:
    - build_linux_gcc

coverage_docker:
  stage: test
  tags:
    - docker
  image: registry.git.vikingsoftware.com/vs/ci-images/ubuntu_bionic_qt5.11.1_cpp:latest
  script:
    - apt-get update -yq
    - apt-get install -y uuid-dev default-jre
    - mkdir -p build_coverage; cd build_coverage
    - qmake CONFIG+=debug CONFIG+=coverage -recursive ..
    - make -j 8
    - export QT_QPA_PLATFORM=offscreen
    - make coverage-html
  coverage: '/^ *lines\.*:\s+(\d+.\d+\%)/'
  artifacts:
    paths:
      - build_coverage/coverage-html
    expire_in: 1 week
