stages:
  - build

build_debian10_gcc:
  stage: build
  tags:
    - docker
  image: registry.git.vikingsoftware.com/esa/taste3-ci-image:latest
  script:
    - mkdir -p build; cd build
    - qmake -recursive ..
    - make -j 8
